sudo: required
language: node_js
node_js:
  - "lts/*"
notifications:
  email:
    recipients:
    - ${MAINTAINER_EMAIL}
services:
  - docker
stages:
  - build_dependencies
  - test
  - name: release
    if: branch =~ ^release\-[.]+$
jobs:
  include:
  - stage: build_dependencies
    script:
    - cat package.json | jq '.dependencies,.devDependencies' | md5sum -q > ./.dependency_hash
    - npm run build-deps -- "$(cat ./.dependency_hash)" "development"
    - docker login -u ${DH_USERNAME} -p ${DH_PASSWORD}
    - docker push zephinzer/annams:dependency-set-$(cat ./.dependency_hash)
    - docker logout
  - stage: build_dependencies
    script:
    - cat package.json | jq '.dependencies,.devDependencies' | md5sum -q > ./.dependency_hash
    - npm run build-deps -- "$(cat ./.dependency_hash)"
    - docker login -u ${DH_USERNAME} -p ${DH_PASSWORD}
    - docker push zephinzer/annams:dependency-set-$(cat ./.dependency_hash)
    - docker logout
  - stage: build_application
    script:
    - git log -n 1 --format='%H' > ./.commit_hash
    - npm run build
    - docker tag zephinzer/annams:latest zephinzer/annams:$(cat ./.commit_hash)
    - docker login -u ${DH_USERNAME} -p ${DH_PASSWORD}
    - docker push zephinzer/annams:latest
    - docker push zephinzer/annams:$(cat ./.commit_hash)
    - docker logout