sudo: required
language: node_js
node_js:
  - "lts/*"
notifications:
  email:
    recipients:
    - "${MAINTAINER_EMAIL}"
services:
  - docker
stages:
  - "Build Dependencies"
  - "Build Application"
  - test
  - name: release
    if: branch =~ ^release\-[.]+$
jobs:
  include:
  - stage: "Build Dependencies"
    script:
    - cat package.json | jq '.dependencies,.devDependencies' | md5sum | cut -f 1 -d ' ' > ./.dependency_hash
    - ENV=development npm run build-deps -- "$(cat ./.dependency_hash)"
    - docker login -u ${DH_USERNAME} -p ${DH_PASSWORD}
    - docker push zephinzer/annams:deps-development-$(cat ./.dependency_hash)
    - docker logout
  - stage: "Build Dependencies"
    script:
    - cat package.json | jq '.dependencies,.devDependencies' | md5sum | cut -f 1 -d ' '  > ./.dependency_hash
    - ENV=production npm run build-deps -- "$(cat ./.dependency_hash)"
    - docker login -u ${DH_USERNAME} -p ${DH_PASSWORD}
    - docker push zephinzer/annams:deps-production-$(cat ./.dependency_hash)
    - docker logout
  - stage: "Build Application"
    script:
    - git log -n 1 --format='%H' > ./.commit_hash
    - ENV=development npm run build
    - docker tag zephinzer/annams:development-latest zephinzer/annams:dev-$(cat ./.commit_hash)
    - docker login -u ${DH_USERNAME} -p ${DH_PASSWORD}
    - docker push zephinzer/annams:development-latest
    - docker push zephinzer/annams:dev-$(cat ./.commit_hash)
    - docker logout
  - stage: "Build Application"
    script:
    - git log -n 1 --format='%H' > ./.commit_hash
    - ENV=production npm run build
    - docker tag zephinzer/annams:production-latest zephinzer/annams:$(cat ./.commit_hash)
    - docker login -u ${DH_USERNAME} -p ${DH_PASSWORD}
    - docker push zephinzer/annams:production-latest
    - docker push zephinzer/annams:$(cat ./.commit_hash)
    - docker logout
  - stage: test
    script:
    - git log -n 1 --format='%H' > ./.commit_hash
    - export ANNAMS_DEV_IMAGE="zephinzer/annams:dev-$(cat ./.commit_hash)"
    - docker pull "${ANNAMS_DEV_IMAGE}"
    - docker-compose -f ./provisioning/deployments/docker/test/docker-compose.yml run test-lint
  - stage: test
    script:
    - git log -n 1 --format='%H' > ./.commit_hash
    - export ANNAMS_DEV_IMAGE="zephinzer/annams:dev-$(cat ./.commit_hash)"
    - docker pull "${ANNAMS_DEV_IMAGE}"
    - docker-compose -f ./provisioning/deployments/docker/test/docker-compose.yml run test-sec
  - stage: test
    script:
    - git log -n 1 --format='%H' > ./.commit_hash
    - export ANNAMS_DEV_IMAGE="zephinzer/annams:dev-$(cat ./.commit_hash)"
    - docker pull "${ANNAMS_DEV_IMAGE}"
    - docker-compose -f ./provisioning/deployments/docker/test/docker-compose.yml run test